### ISSUE TITLE
Sublime 3?

### ISSUE THREAD

**Issue by matanox** [zoncoen/Sublime2Ginger#1]
Any idea if this should work on Sublime Text 3?

**Comment by zoncoen** [comment]
@matanster Sorry, I don't use Sublime Text now. However it should be updated I think. I try to develop it on this weekend. (Of course patches welcome!)

**Comment by deepakshinde** [comment]
Any update on this?

**Comment by zoncoen** [comment]
Released https://github.com/zoncoen/Sublime2Ginger/releases/tag/v3.0.
